---
title: "What is this?"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
This is where you will find all of the exercises related to the R for data analysis course. This course is intended for people who already have some statistical background and who would like to learn how to conduct data analysis using R. This means that we will spend most of the time figuring out *how* to do different data wrangling and statistical analysis steps in R, with the assumption that if you're taking this course, you already know *why* we do these things. 

This course does not assume any prior experience with R or even with programming, and I do my best to explain the basic concepts in a beginner friendly manner. This course will also work for people who have a little bit of coding experience in some other language (e.g. Matlab, python) but are not confident about their ability to pick up a new language or who would also like to recap the basics of writing data analysis scripts. If you have extensive programming experience, this material will likely be too simplistic for you and you might be better off learning R from materials like [R bloggers](https://www.r-bloggers.com/).

There are four exercise sets in total, corresponding to four sets of lecture/demo videos. Because learning programming is hard and especially as a beginner it can be really difficult to know if your solution is almost right or completely off the mark, model solutions for the exercises are also available. You can take a look at them if you get stuck - the aim is for you to learn and discover what you can do with R, not get discouraged by the first error message. Apart from the model solutions, feel free to use as much google as you wish when doing the exercises. Googling for solutions to programming challenges is a valuable skill and people who program for a living use google constantly to check how to do something or what an error message means.

The final assignment which is relevant to those of you who participated in the  Helsinki University, Spring 2021 execution of this course and wish to get course credit.

## Fantastic online resources for learning how to do data analysis in R
* [R for data science (free ebook)](https://r4ds.had.co.nz/)
* [YaRrr! The pirate's guide to R](https://bookdown.org/ndphillips/YaRrr/)
* [Exploratory data analysis with R](https://bookdown.org/rdpeng/exdata/)
* [Data Visualisation in R (course materials)](https://data-vis-2021.djnavarro.net/materials/)

## Some resources for learning stats (with or without R)

As we'll discuss during the course, it is important you know enough statistics when doing analyses with R. R will not babysit you, so you need to make sure you're able to make reasonable, justifiable statistical choices. This topic is beyond the scope of this course, but in case you feel unsure about your stats know-how, here are some free online resources I like:

* [Improving your statistical inferences (Coursera)](https://www.coursera.org/learn/statistical-inferences) (You can always get access to Coursera course materials for free if you select 'audit')
* [Learning Statistics with R (course materials)](https://learningstatisticswithr.com/)
* [Seeing theory, a visual introduction to probability and statistics](https://seeing-theory.brown.edu/index.html)

## Contact
If you have questions or comments, you can reach me by email at juulia dot suvilehto at iki dot fi or [as JSuvilehto on Twitter](https://twitter.com/JSuvilehto). If you find an error in the tasks or solutions, I'd be very happy if you can [submit it as an issue](https://github.com/jtsuvile/R_for_science/issues), or if you're not comfortable with GitHub, just send me a message.
